name: Publish

on: 
  workflow_call:

jobs:
  
  pypi_release_deployment:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install PDM
      uses: pdm-project/setup-pdm@v2
      with:
        enable-pep582: true

    - name: Install Dependencies
      run: pdm install

    - name: Build
      run: pdm build -d dist

    - name: Publish
      uses: pypa/gh-action-pypi-publish@v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}