name: Publish Development

on:
  workflow_call:

jobs:

  update_draft_release:

    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  pypi_test_deployment:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install PDM
      uses: pdm-project/setup-pdm@v2
      with:
        python-version: '3.10'
        enable-pep582: true

    - name: Install Dependencies
      run: pdm install

    - name: Build
      run: pdm build -d dist

    - name: Publish
      uses: pypa/gh-action-pypi-publish@v1
      with:
        user: __token__
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/