name: Python Merge

on:
  workflow_call:
    inputs:
      repository_url:
        required: true
        type: string
    secrets:
      PYPI_API_TOKEN:
        required: true
jobs:
  pypi_development_deployment:
    runs-on: ubuntu-latest

    steps:
      # Fetch the entire history so we can search for the latest tag
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Gather Tag Information
        id: tag-info
        uses: Synodic-Software/Tag-Metadata@v1

      - name: Draft
        id: draft-release
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: "3.12"
          cache: true

      - name: Set Tag
        id: set-tag
        run: |
          version=${{steps.tag-info.outputs.next-tag}}.dev${{steps.tag-info.outputs.height}}
          echo "version=${version}" >> $GITHUB_OUTPUT

      - name: Tag Development Version
        env:
          TAG: ${{steps.set-tag.outputs.version}}
        run: git tag $TAG

      - name: Build
        run: pdm build -d dist

      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          repository-url: ${{ inputs.repository_url }}
